// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/database-types';

const SUPABASE_URL = "https://jzkzqpeorsehwvwcyjkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6a3pxcGVvcnNlaHd2d2N5amtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDI2OTEsImV4cCI6MjA3MDA3ODY5MX0.OOKl6Ca1TDizU-BUr3xk-M9jWcu27taOJTomPJ79Jsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});